version: '3.8'

services:
  peta:
    build:
      context: ..
      dockerfile: development/server.dockerfile
    ports:
      - 3000:3000
    command: air -c /air/.air.toml
    volumes:
      - "../server/:/github.com/oribe1115/peta"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: mariadb
      DB_PORT: 3306
      DB_DATABASE: peta
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: peta
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 60
