package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/oribe1115/peta/graph/gmodel"
)

// CreatePaste is the resolver for the createPaste field.
func (r *mutationResolver) CreatePaste(ctx context.Context, input gmodel.NewPaste) (*gmodel.Paste, error) {
	panic(fmt.Errorf("not implemented: CreatePaste - createPaste"))
}

// Paste is the resolver for the paste field.
func (r *queryResolver) Paste(ctx context.Context, id string) (*gmodel.Paste, error) {
	panic(fmt.Errorf("not implemented: Paste - paste"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
