// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

import (
	"time"
)

type NewPaste struct {
	Title    string  `json:"title"`
	Content  string  `json:"content"`
	Language *string `json:"language,omitempty"`
}

type Paste struct {
	ID        string    `json:"id"`
	Author    string    `json:"author"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Language  *string   `json:"language,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}
